using Shouldly;
using SqlSource.Parsing;
using SqlSource.Snapshot;
using Xunit;
using static SqlSource.Tests.Snapshot.TestSidecars;

namespace SqlSource.Tests.Snapshot;

public class SidecarModelTests
{
    // Phase 5 caches these records in the generator's pipeline, so two that hold the same values must be equal.
    [Fact]
    public void Sidecar_SameValuesInSeparateInstances_AreEqual()
    {
        static Sidecar Create(string label = "active") =>
            SidecarOf(
                Entry(
                    matchesTable: new SidecarTable("public", "users"),
                    parameters:
                    [
                        Parameter(
                            0,
                            "statuses",
                            Postgres(
                                "public.user_status[]",
                                SidecarValues.Kind.Array,
                                "public",
                                "_user_status",
                                element: Postgres(
                                    "public.user_status",
                                    SidecarValues.Kind.Enum,
                                    "public",
                                    "user_status",
                                    labels: [label, "deleted"]
                                )
                            )
                        ),
                    ],
                    columns:
                    [
                        Column(0, "id", Postgres(), origin: new SidecarOrigin("public", "users", "id"), identity: true),
                    ]
                ),
                Entry(
                    "Other",
                    engine: SidecarValues.Engine.SqlServer,
                    columns: [Column(0, "Id", SqlServer(userType: new SqlServerUserType("dbo", "CustomerId", null)))]
                ),
                Entry("Third", engine: "sqlite", columns: [Column(0, "id", new OtherEngineType("INTEGER"))])
            );

        Create().ShouldBe(Create());
        Create().GetHashCode().ShouldBe(Create().GetHashCode());
        Create().ShouldNotBe(Create("suspended"));
    }

    [Fact]
    public void Find_NameOfAnEntry_ReturnsIt()
    {
        var sidecar = SidecarOf(Entry("GetUser"), Entry("ListUsers", hash: "other"));

        sidecar.Find("ListUsers").ShouldNotBeNull().Hash.ShouldBe("other");
    }

    [Theory]
    [InlineData("Missing")]
    // Names are compared ordinally.
    [InlineData("getuser")]
    [InlineData("")]
    public void Find_NameOfNoEntry_ReturnsNull(string name) => SidecarOf(Entry("GetUser")).Find(name).ShouldBeNull();

    [Theory]
    [InlineData("base", nameof(PostgresTypeKind.Base))]
    [InlineData("array", nameof(PostgresTypeKind.Array))]
    [InlineData("domain", nameof(PostgresTypeKind.Domain))]
    [InlineData("enum", nameof(PostgresTypeKind.Enum))]
    [InlineData("range", nameof(PostgresTypeKind.Range))]
    [InlineData("multirange", nameof(PostgresTypeKind.Multirange))]
    [InlineData("composite", nameof(PostgresTypeKind.Composite))]
    public void TryGetKind_KindOfTheFormat_ReturnsIt(string kind, string expected)
    {
        Postgres(kind: kind).TryGetKind(out var found).ShouldBeTrue();

        found.ToString().ShouldBe(expected);
    }

    [Theory]
    [InlineData("pseudo")]
    [InlineData("Base")]
    [InlineData("")]
    public void TryGetKind_AnyOtherValue_ReturnsFalse(string kind) =>
        Postgres(kind: kind).TryGetKind(out _).ShouldBeFalse();

    [Theory]
    [InlineData("Queries/Users.sql", "Queries/Users.sql.json")]
    [InlineData(@"C:\app\Users.sql", @"C:\app\Users.sql.json")]
    [InlineData("Users.SQL", "Users.SQL.json")]
    public void PathFor_SqlPath_AppendsJson(string sqlPath, string expected) =>
        SidecarFormat.PathFor(sqlPath).ShouldBe(expected);

    [Fact]
    public void SidecarFormat_IsVersionOneOfTheSchemaInTheRepository()
    {
        SidecarFormat.Version.ShouldBe(1);
        SidecarFormat.SchemaId.ShouldBe(
            "https://raw.githubusercontent.com/mbcrawfo/SqlSource/main/schemas/sidecar-v1.schema.json"
        );
        SidecarFormat.Warning.ShouldBe(
            "This file was generated by the 'dotnet sqlsource' tool.  "
                + "Do not edit by hand; use the tool to regenerate it."
        );
    }

    // Snapshot/ may not use Parsing/, so the two engines' names are written twice.  This holds them together.
    [Fact]
    public void Engine_Names_AreTheCanonicalNamesOfTheDialects()
    {
        SidecarValues.Engine.Postgres.ShouldBe(SqlDialectName.Canonical(SqlDialect.PostgreSql));
        SidecarValues.Engine.SqlServer.ShouldBe(SqlDialectName.Canonical(SqlDialect.SqlServer));
    }
}
