namespace SqlSource.Snapshot;

/// <summary>What is fixed for the format this version reads and writes.</summary>
internal static class SidecarFormat
{
    /// <summary>The format version.</summary>
    public const int Version = 1;

    /// <summary>The value of <c>$schema</c>, and the <c>$id</c> of <c>schemas/sidecar-v1.schema.json</c>.</summary>
    public const string SchemaId =
        "https://raw.githubusercontent.com/mbcrawfo/SqlSource/main/schemas/sidecar-v1.schema.json";

    /// <summary>The value of <c>_WARNING</c>, the first line a reader of a file sees.</summary>
    public const string Warning =
        "This file was generated by the 'dotnet sqlsource' tool.  Do not edit by hand; use the tool to regenerate it.";

    /// <summary>The path of the sidecar of a <c>.sql</c> file: the file's path and <c>.json</c>.</summary>
    public static string PathFor(string sqlPath) => sqlPath + ".json";
}
