using Shouldly;
using Xunit;

namespace SqlSource.Tests.Generator;

// The problems of a type's .sql files, and of its queries taken together.
public class FileDiagnosticsTests
{
    private const string Source = """
        using SqlSource;
        namespace App;
        [SqlQueries]
        public partial class Sample { }
        """;

    private const string EmptySqlClass = """
        // <auto-generated/>
        #nullable enable
        #pragma warning disable CS0108, CS0114 // A query can have the name of an inherited member.

        namespace App
        {
            partial class Sample
            {
                private static class Sql
                {
                }
            }
        }

        """;

    [Fact]
    public void Run_FileWithParserErrors_ReportsEachAtItsLineAndColumnInTheSqlFile()
    {
        var run = GeneratorHarness.Run(
            Source,
            new SqlFile(
                "/app/Repo/Users.sql",
                """
                -- SqlSource: keep-comments shout
                -- name: GetUser
                SELECT 1;

                -- name: get-user
                SELECT 2;
                -- name: GetUser
                SELECT 3;
                """
            )
        );

        run.Diagnostics.ShouldBe([
            "SQLSRC109 /app/Repo/Users.sql(1,29)-(1,34): 'shout' is not a SqlSource directive",
            "SQLSRC103 /app/Repo/Users.sql(5,10)-(5,18): 'get-user' is not a valid query name.  A name is a C# "
                + "identifier that is not a reserved keyword.",
            "SQLSRC104 /app/Repo/Users.sql(7,10)-(7,17): The query name 'GetUser' is used more than once in this file",
        ]);
        run.CompilationErrors.ShouldBeEmpty();
    }

    [Fact]
    public void Run_FileWithAnError_GivesNoMembersAndTheTypeKeepsItsEmptySqlClass()
    {
        var run = GeneratorHarness.Run(Source, new SqlFile("/app/Repo/Users.sql", "SELECT 'unfinished;\n"));

        run.Diagnostics.ShouldBe([
            "SQLSRC101 /app/Repo/Users.sql(1,8)-(1,9): A quoted string or identifier is not closed",
        ]);
        run.Sources["App.Sample.g.cs"].ShouldBe(EmptySqlClass);
        run.CompilationErrors.ShouldBeEmpty();
    }

    [Fact]
    public void Run_OneFileWithAnErrorAmongSeveral_KeepsTheMembersOfTheOthers()
    {
        var run = GeneratorHarness.Run(
            Source,
            new SqlFile("/app/Repo/Broken.sql", "/* open\nSELECT 1;\n"),
            new SqlFile("/app/Repo/Users.sql", "-- name: GetUser\nSELECT 1;\n")
        );

        run.Diagnostics.ShouldBe(["SQLSRC102 /app/Repo/Broken.sql(1,1)-(1,3): A block comment or hint is not closed"]);
        run.Sources["App.Sample.g.cs"].ShouldContain("public const string GetUser = \"SELECT 1;\";");
    }

    [Fact]
    public void Run_FileWhoseNameIsNotAnIdentifier_IsAnErrorAtTheStartOfTheFile()
    {
        var run = GeneratorHarness.Run(Source, new SqlFile("/app/Repo/001_init.sql", "CREATE TABLE t (id int);\n"));

        run.Diagnostics.ShouldBe([
            "SQLSRC105 /app/Repo/001_init.sql(1,1)-(1,1): The file has no '-- name:' marker, and its name "
                + "'001_init.sql' does not give a valid query name.  Add a marker or rename the file.",
        ]);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("-- nothing here\n")]
    public void Run_UnreadableOrEmptyFile_IsAnErrorAndNotAnException(string? text)
    {
        var run = GeneratorHarness.Run(Source, new SqlFile("/app/Repo/Users.sql", text));

        run.Diagnostics.ShouldBe(["SQLSRC113 /app/Repo/Users.sql(1,1)-(1,1): The query has no SQL"]);
        run.Sources["App.Sample.g.cs"].ShouldBe(EmptySqlClass);
    }

    [Fact]
    public void Run_FileSharedByTwoTypes_ReportsItsErrorsOnce()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;
            namespace App;
            [SqlQueries]
            public partial class First { }
            [SqlQueries(Path = "Users.sql")]
            public partial class Second { }
            """,
            new SqlFile("/app/Repo/Users.sql", "-- name: 1x\nSELECT 1;\n")
        );

        run.Diagnostics.ShouldHaveSingleItem().ShouldStartWith("SQLSRC103 /app/Repo/Users.sql(1,10)-(1,12)");
    }

    [Fact]
    public void Run_FileListedTwice_GivesEachMemberAndEachErrorOnce()
    {
        var broken = new SqlFile("/app/Repo/Broken.sql", "-- name: 1x\nSELECT 1;\n");
        var users = new SqlFile("/app/Repo/Users.sql", "-- name: GetUser\nSELECT 1;\n");

        var run = GeneratorHarness.Run(
            Source,
            broken,
            users,
            new SqlFile("/app/Repo/../Repo/broken.SQL", broken.Text),
            new SqlFile("\\app\\Repo\\Users.sql", users.Text)
        );

        run.Diagnostics.ShouldHaveSingleItem().ShouldStartWith("SQLSRC103 /app/Repo/Broken.sql(1,10)-(1,12)");
        run.Sources["App.Sample.g.cs"].Split("public const string GetUser").Length.ShouldBe(2);
        run.CompilationErrors.ShouldBeEmpty();
    }

    [Fact]
    public void Run_FileThatNoTypeClaims_IsIgnoredWithItsErrors()
    {
        var run = GeneratorHarness.Run(
            Source,
            new SqlFile("/app/Repo/Users.sql", "-- name: GetUser\nSELECT 1;\n"),
            new SqlFile("/app/Migrations/001_init.sql", "SELECT 'unfinished;\n"),
            new SqlFile("/app/Repo/Sub/002-more.sql", "/* open\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
    }

    [Fact]
    public void Run_QueryNameUsedInTwoFilesOfOneType_IsAnErrorAtTheSecondAndThatFileGivesNoMembers()
    {
        var run = GeneratorHarness.Run(
            Source,
            new SqlFile("/app/Repo/A.sql", "-- name: GetUser\nSELECT 1;\n"),
            new SqlFile("/app/Repo/B.sql", "-- name: Other\nSELECT 2;\n\n-- name: GetUser\nSELECT 3;\n")
        );

        run.Diagnostics.ShouldBe([
            "SQLSRC008 /app/Repo/B.sql(4,10)-(4,17): The query name 'GetUser' is already used in 'A.sql', which also "
                + "belongs to 'Sample'",
        ]);
        var source = run.Sources["App.Sample.g.cs"];
        source.ShouldContain("public const string GetUser = \"SELECT 1;\";");
        source.ShouldNotContain("Other");
        run.CompilationErrors.ShouldBeEmpty();
    }

    [Fact]
    public void Run_QueryNameUsedInTwoFilesOfDifferentTypes_IsAllowed()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;
            namespace App;
            [SqlQueries(Path = "A.sql")]
            public partial class First { }
            [SqlQueries(Path = "B.sql")]
            public partial class Second { }
            """,
            new SqlFile("/app/Repo/A.sql", "-- name: GetUser\nSELECT 1;\n"),
            new SqlFile("/app/Repo/B.sql", "-- name: GetUser\nSELECT 2;\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
    }

    [Fact]
    public void Run_NestedModeAndAQueryNamedSql_IsAnErrorAtTheQuery()
    {
        var run = GeneratorHarness.Run(Source, new SqlFile("/app/Repo/Sql.sql", "SELECT 1;\n"));

        run.Diagnostics.ShouldBe([
            "SQLSRC009 /app/Repo/Sql.sql(1,1)-(1,1): A query of 'Sample' cannot be named 'Sql', because its member "
                + "would have the name of the type that contains it",
        ]);
        run.Sources["App.Sample.g.cs"].ShouldBe(EmptySqlClass);
        run.CompilationErrors.ShouldBeEmpty();
    }

    [Fact]
    public void Run_DirectModeAndATypeNamedWithAKeyword_LeavesAQueryOfThatNameToTheParser()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;
            namespace App;
            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class @class<T> { }
            """,
            new SqlFile("/app/Repo/Users.sql", "-- name: Sql\nSELECT 1;\n"),
            new SqlFile("/app/Repo/Other.sql", "-- SqlSource: keep-comments\n-- name: class\nSELECT 2;\n")
        );

        // "class" is a reserved keyword, so the parser has already refused it as a name.
        run.Diagnostics.ShouldHaveSingleItem().ShouldStartWith("SQLSRC103 /app/Repo/Other.sql(2,10)-(2,15)");
        run.Sources["App.class-1.g.cs"].ShouldContain("public const string Sql = \"SELECT 1;\";");
    }

    [Fact]
    public void Run_DirectModeAndAQueryNamedLikeTheType_IsAnErrorAndItsFileGivesNoMembers()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;
            namespace App;
            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample { }
            """,
            new SqlFile("/app/Repo/A.sql", "-- name: Kept\nSELECT 1;\n"),
            new SqlFile("/app/Repo/B.sql", "-- name: Dropped\nSELECT 2;\n-- name: Sample\nSELECT 3;\n")
        );

        run.Diagnostics.ShouldBe([
            "SQLSRC009 /app/Repo/B.sql(3,10)-(3,16): A query of 'Sample' cannot be named 'Sample', because its member "
                + "would have the name of the type that contains it",
        ]);
        var source = run.Sources["App.Sample.g.cs"];
        source.ShouldContain("public const string Kept = \"SELECT 1;\";");
        source.ShouldNotContain("Dropped");
        run.CompilationErrors.ShouldBeEmpty();
    }
}
