using System;
using System.Linq;
using Shouldly;
using SqlSource.Generation;
using Xunit;

namespace SqlSource.Tests.Generator;

public class GeneratedSourceTests
{
    private static readonly SqlFile Users = new("/app/Repo/Users.sql", "-- name: GetUser\nSELECT 1;\n");

    [Fact]
    public void Run_NoAttributedType_EmitsOnlyTheAttribute()
    {
        var run = GeneratorHarness.Run("public class Sample;", Users);

        run.Sources.Keys.ShouldBe(["SqlQueriesAttribute.g.cs"]);
        run.Sources["SqlQueriesAttribute.g.cs"].ShouldBe(AttributeSource.Text);
        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
    }

    [Fact]
    public void Run_NestedMode_PutsTheConstantsInAPrivateSqlClass()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries]
            public partial class Sample
            {
                public static string First => Sql.GetUser;

                public static string Second => Sql.ListUsers;
            }
            """,
            new SqlFile(
                "/app/Repo/Users.sql",
                """
                -- Queries for users.
                -- name: GetUser
                -- summary: Loads one user by id.
                SELECT id, name -- the columns
                FROM users
                WHERE id = @id;

                -- name: ListUsers
                SELECT id, name FROM users;
                """
            )
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources.Keys.ShouldBe(["SqlQueriesAttribute.g.cs", "App.Sample.g.cs"], ignoreOrder: true);
        run.Sources["App.Sample.g.cs"]
            .ShouldBe(
                """
                // <auto-generated/>
                #nullable enable

                namespace App
                {
                    partial class Sample
                    {
                        private static class Sql
                        {
                            /// <summary>
                            /// Loads one user by id.
                            /// </summary>
                            /// <remarks>
                            /// <code>
                            /// SELECT id, name
                            /// FROM users
                            /// WHERE id = @id;
                            /// </code>
                            /// </remarks>
                            public const string GetUser = "SELECT id, name\nFROM users\nWHERE id = @id;";

                            /// <summary>
                            /// The <c>ListUsers</c> query from <c>Users.sql</c>.
                            /// </summary>
                            /// <remarks>
                            /// <code>
                            /// SELECT id, name FROM users;
                            /// </code>
                            /// </remarks>
                            public const string ListUsers = "SELECT id, name FROM users;";
                        }
                    }
                }

                """
            );
    }

    [Fact]
    public void Run_DirectMode_PutsTheConstantsOnTheType()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public static partial class Sample;

            public static class Consumer
            {
                public const string Value = Sample.GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Sample.g.cs"]
            .ShouldBe(
                """
                // <auto-generated/>
                #nullable enable

                namespace App
                {
                    partial class Sample
                    {
                        /// <summary>
                        /// The <c>GetUser</c> query from <c>Users.sql</c>.
                        /// </summary>
                        /// <remarks>
                        /// <code>
                        /// SELECT 1;
                        /// </code>
                        /// </remarks>
                        public const string GetUser = "SELECT 1;";
                    }
                }

                """
            );
    }

    [Theory]
    [InlineData("public partial class Sample", "partial class Sample")]
    [InlineData("public static partial class Sample", "partial class Sample")]
    [InlineData("public abstract partial class Sample", "partial class Sample")]
    [InlineData("internal sealed partial class Sample", "partial class Sample")]
    [InlineData("public partial struct Sample", "partial struct Sample")]
    [InlineData("public readonly partial struct Sample", "partial struct Sample")]
    [InlineData("public ref partial struct Sample", "partial struct Sample")]
    [InlineData("public partial record Sample", "partial record Sample")]
    [InlineData("public partial record class Sample", "partial record Sample")]
    [InlineData("public partial record struct Sample", "partial record struct Sample")]
    [InlineData("public readonly partial record struct Sample", "partial record struct Sample")]
    [InlineData("public partial class Sample<T>", "partial class Sample<T>")]
    [InlineData(
        "public partial class Sample<TKey, TValue> where TKey : notnull where TValue : class, new()",
        "partial class Sample<TKey, TValue>"
    )]
    [InlineData(
        "public partial class Sample<[System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(0)] @in>",
        "partial class Sample<@in>"
    )]
    public void Run_EachKindOfType_RepeatsItsKeywordNameAndTypeParameters(string declaration, string expected)
    {
        var run = GeneratorHarness.Run(
            $$"""
            using SqlSource;

            namespace App;

            [SqlQueries]
            {{declaration}}
            {
                public static string Value => Sql.GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources.Single(source => source.Key.StartsWith("App.Sample", StringComparison.Ordinal))
            .Value.ShouldContain("namespace App\n{\n    " + expected + "\n    {\n        private static class Sql\n");
    }

    [Fact]
    public void Run_NestedType_RepeatsEachContainingType()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App.Data
            {
                public static partial class Outer
                {
                    public partial interface IMiddle<TKey, TValue>
                    {
                        [SqlQueries]
                        private partial record Inner
                        {
                            public static string Value => Sql.GetUser;
                        }
                    }
                }
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Data.Outer.IMiddle-2.Inner.g.cs"]
            .ShouldBe(
                """
                // <auto-generated/>
                #nullable enable

                namespace App.Data
                {
                    partial class Outer
                    {
                        partial interface IMiddle<TKey, TValue>
                        {
                            partial record Inner
                            {
                                private static class Sql
                                {
                                    /// <summary>
                                    /// The <c>GetUser</c> query from <c>Users.sql</c>.
                                    /// </summary>
                                    /// <remarks>
                                    /// <code>
                                    /// SELECT 1;
                                    /// </code>
                                    /// </remarks>
                                    public const string GetUser = "SELECT 1;";
                                }
                            }
                        }
                    }
                }

                """
            );
    }

    [Fact]
    public void Run_TypeInTheGlobalNamespaceNamedWithAKeyword_HasNoNamespaceBlockAndKeepsTheEscape()
    {
        var run = GeneratorHarness.Run(
            """
            [SqlSource.SqlQueries(Mode = SqlSource.SqlQueriesMode.Direct)]
            public partial struct @class
            {
                public static string Value => GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["class.g.cs"]
            .ShouldBe(
                """
                // <auto-generated/>
                #nullable enable

                partial struct @class
                {
                    /// <summary>
                    /// The <c>GetUser</c> query from <c>Users.sql</c>.
                    /// </summary>
                    /// <remarks>
                    /// <code>
                    /// SELECT 1;
                    /// </code>
                    /// </remarks>
                    public const string GetUser = "SELECT 1;";
                }

                """
            );
    }

    [Fact]
    public void Run_NamespaceWithAnEscapedKeyword_KeepsTheEscapeInCode()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App.@event
            {
                namespace Data
                {
                    [SqlQueries]
                    public partial class Sample
                    {
                        public static string Value => Sql.GetUser;
                    }
                }
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.event.Data.Sample.g.cs"].ShouldContain("namespace App.@event.Data\n{\n");
    }

    [Fact]
    public void Run_TypesThatDifferByNamespaceOrArity_GetTheirOwnFiles()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App
            {
                [SqlQueries]
                public partial class Sample;

                [SqlQueries]
                public partial class Sample<T>;
            }

            namespace Other
            {
                [SqlQueries]
                public partial class Sample;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources.Keys.ShouldBe(
            ["SqlQueriesAttribute.g.cs", "App.Sample.g.cs", "App.Sample-1.g.cs", "Other.Sample.g.cs"],
            ignoreOrder: true
        );
    }

    [Fact]
    public void Run_SeveralFiles_OrdersMembersByFilePathIgnoringCaseThenByPositionInTheFile()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample;
            """,
            new SqlFile("/app/Repo/c.sql", "-- name: Fifth\nSELECT 5;\n"),
            new SqlFile("/app/Repo/B.sql", "-- name: Third\nSELECT 3;\n-- name: Fourth\nSELECT 4;\n"),
            new SqlFile("/app/Repo/a.sql", "-- name: Second\nSELECT 2;\n"),
            new SqlFile("/app/Repo/A_First.SQL", "SELECT 1;\n"),
            new SqlFile("/app/Repo/Sub/Nested.sql", "SELECT 0;\n"),
            new SqlFile("/app/Other/Elsewhere.sql", "SELECT 0;\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Sample.g.cs"]
            .Split('\n')
            .Where(line => line.Contains("public const string", StringComparison.Ordinal))
            .Select(line => line.Trim())
            .ShouldBe([
                "public const string Second = \"SELECT 2;\";",
                "public const string A_First = \"SELECT 1;\";",
                "public const string Third = \"SELECT 3;\";",
                "public const string Fourth = \"SELECT 4;\";",
                "public const string Fifth = \"SELECT 5;\";",
            ]);
    }

    [Theory]
    [InlineData("../Queries/Users.sql", "FromQueriesUsers")]
    [InlineData("..\\Queries\\USERS.SQL", "FromQueriesUsers")]
    [InlineData("../Queries", "FromQueriesOrders", "FromQueriesUsers")]
    [InlineData("Sub", "FromSub")]
    [InlineData("./Sub/", "FromSub")]
    [InlineData("", "FromRepo")]
    public void Run_Path_SelectsAFileOrTheFilesOfAFolder(string path, params string[] expectedMembers)
    {
        var run = GeneratorHarness.Run(
            $$"""
            using SqlSource;

            namespace App;

            [SqlQueries(Path = @"{{path}}", Mode = SqlQueriesMode.Direct)]
            public partial class Sample;
            """,
            new SqlFile("/app/Repo/Users.sql", "-- name: FromRepo\nSELECT 1;\n"),
            new SqlFile("/app/Repo/Sub/Users.sql", "-- name: FromSub\nSELECT 2;\n"),
            new SqlFile("/app/Queries/Users.sql", "-- name: FromQueriesUsers\nSELECT 3;\n"),
            new SqlFile("/app/Queries/Orders.sql", "-- name: FromQueriesOrders\nSELECT 4;\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Sample.g.cs"]
            .Split('\n')
            .Where(line => line.Contains("public const string", StringComparison.Ordinal))
            .Select(line => line.Trim().Split(' ')[3])
            .ShouldBe(expectedMembers);
    }

    [Fact]
    public void Run_WindowsPaths_ResolveTheSameWay()
    {
        var run = GeneratorHarness.Run(
            [
                new SourceFile(
                    @"C:\app\Repo\Sample.cs",
                    "[SqlSource.SqlQueries]\npublic partial class Sample { public string Value => Sql.GetUser; }\n"
                ),
            ],
            [new SqlFile(@"c:\App\repo\Users.sql", "-- name: GetUser\nSELECT 1;\n")]
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["Sample.g.cs"].ShouldContain("/// The <c>GetUser</c> query from <c>Users.sql</c>.\n");
    }

    [Fact]
    public void Run_FileSharedByTwoTypes_GivesBothItsConstants()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries]
            public partial class First
            {
                public static string Value => Sql.GetUser;
            }

            [SqlQueries(Path = "Users.sql", Mode = SqlQueriesMode.Direct)]
            public partial class Second
            {
                public static string Value => GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.First.g.cs"].ShouldContain("public const string GetUser = \"SELECT 1;\";");
        run.Sources["App.Second.g.cs"].ShouldContain("public const string GetUser = \"SELECT 1;\";");
    }

    [Fact]
    public void Run_QueryWithTokens_GetsNoMemberAndNoDiagnosticWhileTheOthersOfItsFileDo()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample;
            """,
            new SqlFile(
                "/app/Repo/Users.sql",
                "-- name: GetUser\nSELECT 1;\n-- name: ListFrom\nSELECT * FROM {{table}};\n-- name: Count\nSELECT 3;\n"
            )
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        var source = run.Sources["App.Sample.g.cs"];
        source.ShouldContain("public const string GetUser = \"SELECT 1;\";");
        source.ShouldContain("public const string Count = \"SELECT 3;\";");
        source.ShouldNotContain("ListFrom");
    }

    [Fact]
    public void Run_SqlThatNeedsEscaping_CompilesAndKeepsItsValue()
    {
        // A quoted region is copied as written, so it can hold a quote, a backslash, a tab, characters XML reserves,
        // and a character that C# treats as a line terminator.
        const string Sql = "SELECT \"a\", 'b\\c', '\t', '<&>', '\u2028\u0085' WHERE x < 1;";

        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample;
            """,
            new SqlFile("/app/Repo/Users.sql", "-- summary: a < b & c\n" + Sql + "\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        var source = run.Sources["App.Sample.g.cs"];
        source.ShouldContain("/// a &lt; b &amp; c\n");
        source.ShouldContain(
            "public const string Users = \"SELECT \\\"a\\\", 'b\\\\c', '\\t', '<&>', '\\u2028\\u0085' WHERE x < 1;\";\n"
        );
    }

    [Fact]
    public void Run_PublicTypeInAProjectThatDocumentsItsApi_GetsNoWarningForAGeneratedMember()
    {
        // A consumer that treats CS1591, a public member without documentation, as an error must not be broken by
        // generated code.  Here the consumer's own members are documented, so any CS1591 comes from the generator.
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            /// <summary>Queries.</summary>
            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample;

            /// <summary>More queries.</summary>
            [SqlQueries]
            public partial struct Other;
            """,
            new SqlFile("/app/Repo/Users.sql", "-- name: GetUser\n-- summary: x < y & z\nSELECT 1 WHERE a < b;\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources.Keys.ShouldContain("App.Sample.g.cs");
    }

    [Fact]
    public void Run_NonAsciiNames_AreKept()
    {
        var run = GeneratorHarness.Run(
            [
                new SourceFile(
                    "/app/Dépôt/Sample.cs",
                    "namespace Données;\n[SqlSource.SqlQueries]\n"
                        + "public partial class Requêtes { public string V => Sql.Größe; }\n"
                ),
            ],
            [new SqlFile("/app/Dépôt/Größe.sql", "SELECT 'ñ 😀';\n")]
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["Données.Requêtes.g.cs"].ShouldContain("public const string Größe = \"SELECT 'ñ 😀';\";");
    }

    [Fact]
    public void Run_AttributeOnTwoPartialDeclarations_IsLeftToTheCompilerAndTheTypeGetsOneFile()
    {
        var run = GeneratorHarness.Run(
            [
                new SourceFile("/app/Repo/Sample.cs", "[SqlSource.SqlQueries]\npublic partial class Sample;\n"),
                new SourceFile("/app/Other/Sample.cs", "[SqlSource.SqlQueries]\npublic partial class Sample;\n"),
            ],
            [Users, new SqlFile("/app/Other/Orders.sql", "SELECT 2;\n")]
        );

        run.Diagnostics.ShouldBeEmpty();
        run.Sources.Keys.ShouldBe(["SqlQueriesAttribute.g.cs", "Sample.g.cs"], ignoreOrder: true);
        run.Sources["Sample.g.cs"].ShouldContain("public const string GetUser");
        run.CompilationErrors.ShouldHaveSingleItem().ShouldStartWith("CS0579 /app/Other/Sample.cs(1,2)");
    }
}
