using System;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp;
using Shouldly;
using SqlSource.Generation;
using Xunit;

namespace SqlSource.Tests.Generator;

public class GeneratedSourceTests
{
    private static readonly SqlFile Users = new("/app/Repo/Users.sql", "-- name: GetUser\nSELECT 1;\n");

    [Fact]
    public void Run_NoAttributedType_EmitsOnlyTheAttribute()
    {
        var run = GeneratorHarness.Run("public class Sample;", Users);

        run.Sources.Keys.ShouldBe(["SqlQueriesAttribute.g.cs"]);
        run.Sources["SqlQueriesAttribute.g.cs"].ShouldBe(AttributeSource.Text);
        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
    }

    [Fact]
    public void Run_NestedMode_PutsTheConstantsInAPrivateSqlClass()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries]
            public partial class Sample
            {
                public static string First => Sql.GetUser;

                public static string Second => Sql.ListUsers;
            }
            """,
            new SqlFile(
                "/app/Repo/Users.sql",
                """
                -- Queries for users.
                -- name: GetUser
                -- summary: Loads one user by id.
                SELECT id, name -- the columns
                FROM users
                WHERE id = @id;

                -- name: ListUsers
                SELECT id, name FROM users;
                """
            )
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources.Keys.ShouldBe(["SqlQueriesAttribute.g.cs", "App.Sample.g.cs"], ignoreOrder: true);
        run.Sources["App.Sample.g.cs"]
            .ShouldBe(
                """
                // <auto-generated/>
                #nullable enable
                #pragma warning disable CS0108, CS0114 // A query can have the name of an inherited member.

                namespace App
                {
                    partial class Sample
                    {
                        private static class Sql
                        {
                            /// <summary>
                            /// Loads one user by id.
                            /// </summary>
                            /// <remarks>
                            /// <code>
                            /// SELECT id, name
                            /// FROM users
                            /// WHERE id = @id;
                            /// </code>
                            /// </remarks>
                            public const string GetUser = "SELECT id, name\nFROM users\nWHERE id = @id;";

                            /// <summary>
                            /// The <c>ListUsers</c> query from <c>Users.sql</c>.
                            /// </summary>
                            /// <remarks>
                            /// <code>
                            /// SELECT id, name FROM users;
                            /// </code>
                            /// </remarks>
                            public const string ListUsers = "SELECT id, name FROM users;";
                        }
                    }
                }

                """
            );
    }

    [Fact]
    public void Run_DirectMode_PutsTheConstantsOnTheType()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public static partial class Sample;

            public static class Consumer
            {
                public const string Value = Sample.GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Sample.g.cs"]
            .ShouldBe(
                """
                // <auto-generated/>
                #nullable enable
                #pragma warning disable CS0108, CS0114 // A query can have the name of an inherited member.

                namespace App
                {
                    partial class Sample
                    {
                        /// <summary>
                        /// The <c>GetUser</c> query from <c>Users.sql</c>.
                        /// </summary>
                        /// <remarks>
                        /// <code>
                        /// SELECT 1;
                        /// </code>
                        /// </remarks>
                        public const string GetUser = "SELECT 1;";
                    }
                }

                """
            );
    }

    [Theory]
    [InlineData("public partial class Sample", "partial class Sample")]
    [InlineData("public static partial class Sample", "partial class Sample")]
    [InlineData("public abstract partial class Sample", "partial class Sample")]
    [InlineData("internal sealed partial class Sample", "partial class Sample")]
    [InlineData("public partial struct Sample", "partial struct Sample")]
    [InlineData("public readonly partial struct Sample", "partial struct Sample")]
    [InlineData("public ref partial struct Sample", "partial struct Sample")]
    [InlineData("public partial record Sample", "partial record Sample")]
    [InlineData("public partial record class Sample", "partial record Sample")]
    [InlineData("public partial record struct Sample", "partial record struct Sample")]
    [InlineData("public readonly partial record struct Sample", "partial record struct Sample")]
    [InlineData("public partial class Sample<T>", "partial class Sample<T>")]
    [InlineData(
        "public partial class Sample<TKey, TValue> where TKey : notnull where TValue : class, new()",
        "partial class Sample<TKey, TValue>"
    )]
    [InlineData(
        "public partial class Sample<[System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembers(0)] @in>",
        "partial class Sample<@in>"
    )]
    public void Run_EachKindOfType_RepeatsItsKeywordNameAndTypeParameters(string declaration, string expected)
    {
        var run = GeneratorHarness.Run(
            $$"""
            using SqlSource;

            namespace App;

            [SqlQueries]
            {{declaration}}
            {
                public static string Value => Sql.GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources.Single(source => source.Key.StartsWith("App.Sample", StringComparison.Ordinal))
            .Value.ShouldContain("namespace App\n{\n    " + expected + "\n    {\n        private static class Sql\n");
    }

    [Fact]
    public void Run_NestedType_RepeatsEachContainingType()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App.Data
            {
                public static partial class Outer
                {
                    public partial interface IMiddle<TKey, TValue>
                    {
                        [SqlQueries]
                        private partial record Inner
                        {
                            public static string Value => Sql.GetUser;
                        }
                    }
                }
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Data.Outer.IMiddle-2.Inner.g.cs"]
            .ShouldBe(
                """
                // <auto-generated/>
                #nullable enable
                #pragma warning disable CS0108, CS0114 // A query can have the name of an inherited member.

                namespace App.Data
                {
                    partial class Outer
                    {
                        partial interface IMiddle<TKey, TValue>
                        {
                            partial record Inner
                            {
                                private static class Sql
                                {
                                    /// <summary>
                                    /// The <c>GetUser</c> query from <c>Users.sql</c>.
                                    /// </summary>
                                    /// <remarks>
                                    /// <code>
                                    /// SELECT 1;
                                    /// </code>
                                    /// </remarks>
                                    public const string GetUser = "SELECT 1;";
                                }
                            }
                        }
                    }
                }

                """
            );
    }

    [Fact]
    public void Run_TypeInTheGlobalNamespaceNamedWithAKeyword_HasNoNamespaceBlockAndKeepsTheEscape()
    {
        var run = GeneratorHarness.Run(
            """
            [SqlSource.SqlQueries(Mode = SqlSource.SqlQueriesMode.Direct)]
            public partial struct @class
            {
                public static string Value => GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["class.g.cs"]
            .ShouldBe(
                """
                // <auto-generated/>
                #nullable enable
                #pragma warning disable CS0108, CS0114 // A query can have the name of an inherited member.

                partial struct @class
                {
                    /// <summary>
                    /// The <c>GetUser</c> query from <c>Users.sql</c>.
                    /// </summary>
                    /// <remarks>
                    /// <code>
                    /// SELECT 1;
                    /// </code>
                    /// </remarks>
                    public const string GetUser = "SELECT 1;";
                }

                """
            );
    }

    [Fact]
    public void Run_NamespaceWithAnEscapedKeyword_KeepsTheEscapeInCode()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App.@event
            {
                namespace Data
                {
                    [SqlQueries]
                    public partial class Sample
                    {
                        public static string Value => Sql.GetUser;
                    }
                }
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.event.Data.Sample.g.cs"].ShouldContain("namespace App.@event.Data\n{\n");
    }

    [Fact]
    public void Run_TypesThatDifferByNamespaceOrArity_GetTheirOwnFiles()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App
            {
                [SqlQueries]
                public partial class Sample;

                [SqlQueries]
                public partial class Sample<T>;
            }

            namespace Other
            {
                [SqlQueries]
                public partial class Sample;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources.Keys.ShouldBe(
            ["SqlQueriesAttribute.g.cs", "App.Sample.g.cs", "App.Sample-1.g.cs", "Other.Sample.g.cs"],
            ignoreOrder: true
        );
    }

    [Fact]
    public void Run_SeveralFiles_OrdersMembersByFilePathIgnoringCaseThenByPositionInTheFile()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample;
            """,
            new SqlFile("/app/Repo/c.sql", "-- name: Fifth\nSELECT 5;\n"),
            new SqlFile("/app/Repo/B.sql", "-- name: Third\nSELECT 3;\n-- name: Fourth\nSELECT 4;\n"),
            new SqlFile("/app/Repo/a.sql", "-- name: Second\nSELECT 2;\n"),
            new SqlFile("/app/Repo/A_First.SQL", "SELECT 1;\n"),
            new SqlFile("/app/Repo/Sub/Nested.sql", "SELECT 0;\n"),
            new SqlFile("/app/Other/Elsewhere.sql", "SELECT 0;\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Sample.g.cs"]
            .Split('\n')
            .Where(line => line.Contains("public const string", StringComparison.Ordinal))
            .Select(line => line.Trim())
            .ShouldBe([
                "public const string Second = \"SELECT 2;\";",
                "public const string A_First = \"SELECT 1;\";",
                "public const string Third = \"SELECT 3;\";",
                "public const string Fourth = \"SELECT 4;\";",
                "public const string Fifth = \"SELECT 5;\";",
            ]);
    }

    [Theory]
    [InlineData("../Queries/Users.sql", "FromQueriesUsers")]
    [InlineData("..\\Queries\\USERS.SQL", "FromQueriesUsers")]
    [InlineData("../Queries", "FromQueriesOrders", "FromQueriesUsers")]
    [InlineData("Sub", "FromSub")]
    [InlineData("./Sub/", "FromSub")]
    [InlineData("", "FromRepo")]
    public void Run_Path_SelectsAFileOrTheFilesOfAFolder(string path, params string[] expectedMembers)
    {
        var run = GeneratorHarness.Run(
            $$"""
            using SqlSource;

            namespace App;

            [SqlQueries(Path = @"{{path}}", Mode = SqlQueriesMode.Direct)]
            public partial class Sample;
            """,
            new SqlFile("/app/Repo/Users.sql", "-- name: FromRepo\nSELECT 1;\n"),
            new SqlFile("/app/Repo/Sub/Users.sql", "-- name: FromSub\nSELECT 2;\n"),
            new SqlFile("/app/Queries/Users.sql", "-- name: FromQueriesUsers\nSELECT 3;\n"),
            new SqlFile("/app/Queries/Orders.sql", "-- name: FromQueriesOrders\nSELECT 4;\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Sample.g.cs"]
            .Split('\n')
            .Where(line => line.Contains("public const string", StringComparison.Ordinal))
            .Select(line => line.Trim().Split(' ')[3])
            .ShouldBe(expectedMembers);
    }

    [Fact]
    public void Run_WindowsPaths_ResolveTheSameWay()
    {
        var run = GeneratorHarness.Run(
            [
                new SourceFile(
                    @"C:\app\Repo\Sample.cs",
                    "[SqlSource.SqlQueries]\npublic partial class Sample { public string Value => Sql.GetUser; }\n"
                ),
            ],
            [new SqlFile(@"c:\App\repo\Users.sql", "-- name: GetUser\nSELECT 1;\n")]
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["Sample.g.cs"].ShouldContain("/// The <c>GetUser</c> query from <c>Users.sql</c>.\n");
    }

    [Fact]
    public void Run_FileSharedByTwoTypes_GivesBothItsConstants()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries]
            public partial class First
            {
                public static string Value => Sql.GetUser;
            }

            [SqlQueries(Path = "Users.sql", Mode = SqlQueriesMode.Direct)]
            public partial class Second
            {
                public static string Value => GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.First.g.cs"].ShouldContain("public const string GetUser = \"SELECT 1;\";");
        run.Sources["App.Second.g.cs"].ShouldContain("public const string GetUser = \"SELECT 1;\";");
    }

    [Fact]
    public void Run_QueryWithTokens_IsAMethodBesideTheConstantsOfItsFile()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample
            {
                public static string List() => ListFrom("users", "1 = 1") + GetUser;
            }
            """,
            new SqlFile(
                "/app/Repo/Users.sql",
                """
                -- name: GetUser
                SELECT 1;

                -- name: ListFrom
                -- summary: Lists the rows of a table.
                SELECT id -- the key
                FROM {{ table }} WHERE {{filter}} ORDER BY {{table}}.id;
                """
            )
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Sample.g.cs"]
            .ShouldBe(
                """
                // <auto-generated/>
                #nullable enable
                #pragma warning disable CS0108, CS0114 // A query can have the name of an inherited member.

                namespace App
                {
                    partial class Sample
                    {
                        /// <summary>
                        /// The <c>GetUser</c> query from <c>Users.sql</c>.
                        /// </summary>
                        /// <remarks>
                        /// <code>
                        /// SELECT 1;
                        /// </code>
                        /// </remarks>
                        public const string GetUser = "SELECT 1;";

                        /// <summary>
                        /// Lists the rows of a table.
                        /// </summary>
                        /// <remarks>
                        /// <code>
                        /// SELECT id
                        /// FROM {{table}} WHERE {{filter}} ORDER BY {{table}}.id;
                        /// </code>
                        /// </remarks>
                        /// <param name="table">The text that replaces <c>{{table}}</c>.</param>
                        /// <param name="filter">The text that replaces <c>{{filter}}</c>.</param>
                        public static string ListFrom(string table, string filter)
                        {
                            global::System.ArgumentException.ThrowIfNullOrWhiteSpace(table);
                            global::System.ArgumentException.ThrowIfNullOrWhiteSpace(filter);
                            return string.Create(
                                36 + table.Length * 2 + filter.Length,
                                (table, filter),
                                static (span, state) =>
                                {
                                    "SELECT id\nFROM ".CopyTo(span);
                                    span = span.Slice(15);
                                    state.Item1.CopyTo(span);
                                    span = span.Slice(state.Item1.Length);
                                    " WHERE ".CopyTo(span);
                                    span = span.Slice(7);
                                    state.Item2.CopyTo(span);
                                    span = span.Slice(state.Item2.Length);
                                    " ORDER BY ".CopyTo(span);
                                    span = span.Slice(10);
                                    state.Item1.CopyTo(span);
                                    span = span.Slice(state.Item1.Length);
                                    ".id;".CopyTo(span);
                                }
                            );
                        }
                    }
                }

                """
            );
    }

    [Fact]
    public void Run_QueryWithTokensOnAGenericStructInNestedMode_IsAMethodOfTheSqlClass()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            /// <summary>Queries.</summary>
            [SqlQueries]
            public partial struct Sample<T>
            {
                /// <summary>Uses the query.</summary>
                public static string List() => Sql.ListFrom("users");
            }
            """,
            new SqlFile("/app/Repo/Users.sql", "-- name: ListFrom\nSELECT * FROM {{table}};\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Sample-1.g.cs"]
            .ShouldContain(
                "        private static class Sql\n        {\n            /// <summary>\n"
                    + "            /// The <c>ListFrom</c> query from <c>Users.sql</c>.\n"
            );
        run.Sources["App.Sample-1.g.cs"].ShouldContain("            public static string ListFrom(string table)\n");
    }

    [Fact]
    public void Run_QueryThatIsOnlyATokenOrHasEightOfThem_Compiles()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries]
            public partial class Sample
            {
                public static string Whole() => Sql.Whole("SELECT 1;");

                public static string Eight() => Sql.Eight("1", "2", "3", "4", "5", "6", "7", "8");
            }
            """,
            new SqlFile(
                "/app/Repo/Users.sql",
                "-- name: Whole\n{{sql}}\n"
                    + "-- name: Eight\nSELECT {{a}}{{b}}, {{c}}, {{d}}, {{e}}, {{f}}, {{g}}, {{h}}, {{a}};\n"
            )
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
    }

    // Any identifier that is not a reserved keyword can be a token name.  Each of these is a name the generated method
    // uses itself, a name of something in scope, or a contextual keyword.
    [Theory]
    [InlineData("span")]
    [InlineData("state")]
    [InlineData("span1")]
    [InlineData("Item1")]
    [InlineData("Item2")]
    [InlineData("Rest")]
    [InlineData("System")]
    [InlineData("String")]
    [InlineData("ArgumentException")]
    [InlineData("Sql")]
    [InlineData("Sample")]
    [InlineData("Probe")]
    [InlineData("T")]
    [InlineData("var")]
    [InlineData("dynamic")]
    [InlineData("await")]
    [InlineData("nameof")]
    [InlineData("global")]
    [InlineData("value")]
    [InlineData("scoped")]
    [InlineData("field")]
    [InlineData("_")]
    [InlineData("from")]
    public void Run_TokenWithAnAwkwardName_Compiles(string name)
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries]
            public partial class Sample<T>
            {
                public static string One() => Sql.Probe("a");

                public static string Two() => Sql.Pair("a", "b");
            }
            """,
            new SqlFile(
                "/app/Repo/Users.sql",
                "-- name: Probe\nSELECT {{"
                    + name
                    + "}}, {{"
                    + name
                    + "}};\n"
                    + "-- name: Pair\nSELECT {{"
                    + name
                    + "}} FROM {{second}};\n"
            )
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
    }

    [Fact]
    public void Run_SqlWithATokenThatNeedsEscaping_CompilesAndDocumentsIt()
    {
        // The literal text around a token is escaped like a constant's, in the string and in the comment.
        const string Sql = "SELECT \"a\", 'b\\c', '\t', '<&>', '\u2028\u0085' FROM {{table}} WHERE x < 1;";

        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            /// <summary>Queries.</summary>
            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample;
            """,
            new SqlFile("/app/Repo/Users.sql", Sql + "\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        var source = run.Sources["App.Sample.g.cs"];
        source.ShouldContain("\"SELECT \\\"a\\\", 'b\\\\c', '\\t', '<&>', '\\u2028\\u0085' FROM \".CopyTo(span);\n");
        source.ShouldContain("/// ' FROM {{table}} WHERE x &lt; 1;\n");
    }

    [Fact]
    public void Run_SqlThatNeedsEscaping_CompilesAndKeepsItsValue()
    {
        // A quoted region is copied as written, so it can hold a quote, a backslash, a tab, characters XML reserves,
        // and a character that C# treats as a line terminator.
        const string Sql = "SELECT \"a\", 'b\\c', '\t', '<&>', '\u2028\u0085' WHERE x < 1;";

        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample;
            """,
            new SqlFile("/app/Repo/Users.sql", "-- summary: a < b & c\n" + Sql + "\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        var source = run.Sources["App.Sample.g.cs"];
        source.ShouldContain("/// a &lt; b &amp; c\n");
        source.ShouldContain(
            "public const string Users = \"SELECT \\\"a\\\", 'b\\\\c', '\\t', '<&>', '\\u2028\\u0085' WHERE x < 1;\";\n"
        );
    }

    [Fact]
    public void Run_PublicTypeInAProjectThatDocumentsItsApi_GetsNoWarningForAGeneratedMember()
    {
        // A consumer that treats CS1591, a public member without documentation, as an error must not be broken by
        // generated code.  Here the consumer's own members are documented, so any CS1591 comes from the generator.
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            /// <summary>Queries.</summary>
            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample;

            /// <summary>More queries.</summary>
            [SqlQueries]
            public partial struct Other;
            """,
            new SqlFile("/app/Repo/Users.sql", "-- name: GetUser\n-- summary: x < y & z\nSELECT 1 WHERE a < b;\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources.Keys.ShouldContain("App.Sample.g.cs");
    }

    [Fact]
    public void Run_SqlWithCharactersXmlCannotHold_ReplacesThemInTheCommentAndKeepsTheValue()
    {
        // A form feed and a Ctrl-Z, which old tools leave at the end of a file, are legal in SQL text and in a C#
        // string, and are not legal anywhere in an XML document.
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample;
            """,
            new SqlFile("/app/Repo/Users.sql", "-- summary: a\fb\nSELECT '\f\u001A';\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Sample.g.cs"].ShouldContain("public const string Users = \"SELECT '\\f\\u001A';\";\n");
    }

    [Theory]
    [InlineData(LanguageVersion.CSharp7_3)]
    [InlineData(LanguageVersion.CSharp8)]
    [InlineData(LanguageVersion.CSharp9)]
    public void Run_ProjectOnAnOlderLanguageVersion_CompilesTheGeneratedAttribute(LanguageVersion languageVersion)
    {
        // The attribute goes into every project that references the package, including one that targets an older
        // framework and so defaults to an older language.  Such a project must get SQLSRC003 if it uses the
        // attribute, not a compiler error in a file it did not write.
        var run = GeneratorHarness.Run(
            [new SourceFile(GeneratorHarness.SourcePath, "public class Sample { }")],
            [],
            languageVersion: languageVersion
        );

        run.Sources.Keys.ShouldBe(["SqlQueriesAttribute.g.cs"]);
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
    }

    [Fact]
    public void Run_ProjectThatSeesTheInternalsOfAnotherWithTheGenerator_GetsNoWarningInGeneratedCode()
    {
        // Both assemblies hold the generated attribute and enum.  This one sees both copies, and the compiler warns
        // (CS0436) wherever the name is used: inside the generated attribute itself, unless that file says otherwise.
        var other = GeneratorHarness.CreateReference(
            "Other",
            "[assembly: System.Runtime.CompilerServices.InternalsVisibleTo(\"TestAssembly\")]\n"
                + "public class InOther { }\n"
        );

        var run = GeneratorHarness.Run(
            [new SourceFile(GeneratorHarness.SourcePath, "public class Sample : InOther { }")],
            [],
            references: [other]
        );

        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
    }

    [Theory]
    [InlineData("Nested", "GetType")]
    [InlineData("Nested", "ToString")]
    [InlineData("Nested", "Equals")]
    [InlineData("Nested", "GetHashCode")]
    [InlineData("Nested", "MemberwiseClone")]
    [InlineData("Nested", "ReferenceEquals")]
    [InlineData("Direct", "GetType")]
    [InlineData("Direct", "ToString")]
    [InlineData("Direct", "Equals")]
    public void Run_QueryNamedLikeAMemberOfObject_GetsNoWarningInGeneratedCode(string mode, string name)
    {
        // "GetType" is a likely name for a query on a table of types.  The constant hides the inherited method, which
        // is what was asked for, and the compiler's request to add "new" is one nobody can act on.
        var run = GeneratorHarness.Run(
            $$"""
            using SqlSource;

            namespace App;

            [SqlQueries(Mode = SqlQueriesMode.{{mode}})]
            public partial class Sample;
            """,
            new SqlFile("/app/Repo/Users.sql", "-- name: " + name + "\nSELECT 1;\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["App.Sample.g.cs"].ShouldContain("public const string " + name + " = \"SELECT 1;\";");
    }

    [Fact]
    public void Run_MethodWithTheSignatureOfAnInheritedVirtualMethod_GetsNoWarningInGeneratedCode()
    {
        // A method that has the name and the parameters of a virtual method of a base class hides it, and the compiler
        // asks for "override" or "new" (CS0114).  Nobody can add either to generated code.  A constant never gets this
        // warning; a method can.
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            public class Base
            {
                public virtual string ListFrom(string table) => table;
            }

            [SqlQueries(Mode = SqlQueriesMode.Direct)]
            public partial class Sample : Base;
            """,
            new SqlFile("/app/Repo/Users.sql", "-- name: ListFrom\nSELECT * FROM {{table}};\n")
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
    }

    [Fact]
    public void Run_NestedModeAndAnInheritedMemberNamedSql_GetsNoWarningInGeneratedCode()
    {
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App;

            public class Base
            {
                protected static int Sql => 1;
            }

            [SqlQueries]
            public partial class Sample : Base
            {
                public static string Value => Sql.GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
    }

    [Fact]
    public void Run_TypesAndNamespacesThatDifferOnlyByCase_GetFilesWhoseNamesDifferByMoreThanCase()
    {
        // The compiler compares the names of generated files ignoring case, and refuses the second of two that are
        // equal that way with an exception that costs every type its generated code.
        var run = GeneratorHarness.Run(
            """
            using SqlSource;

            namespace App
            {
                [SqlQueries]
                public partial class Sample { public static string Value => Sql.GetUser; }

                [SqlQueries]
                public partial class sample { public static string Value => Sql.GetUser; }

                [SqlQueries]
                public partial class Other { public static string Value => Sql.GetUser; }
            }

            namespace APP
            {
                [SqlQueries]
                public partial class Sample { public static string Value => Sql.GetUser; }
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.Sources.Count.ShouldBe(5);
        run.Sources.Keys.Distinct(StringComparer.OrdinalIgnoreCase).Count().ShouldBe(5);
        run.Sources.Keys.ShouldContain("App.Other.g.cs");
        run.Sources.Keys.ShouldNotContain("App.Sample.g.cs");
        run.Sources.Values.Count(source => source.Contains("public const string GetUser", StringComparison.Ordinal))
            .ShouldBe(4);
    }

    [Fact]
    public void Run_TypeWhoseFileWouldBeNamedLikeTheAttributes_GetsAnotherName()
    {
        var run = GeneratorHarness.Run(
            """
            [SqlSource.SqlQueries]
            public partial class SqlQueriesAttribute
            {
                public static string Value => Sql.GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.Sources.Count.ShouldBe(2);
        run.Sources["SqlQueriesAttribute.g.cs"].ShouldBe(AttributeSource.Text);
    }

    [Fact]
    public void Run_TypeNameWrittenWithAUnicodeEscape_GetsAFileNamedByTheCharacter()
    {
        // "\u0053ample" is the identifier Sample.  The escape is legal in code and not in the name of a file.
        var run = GeneratorHarness.Run(
            """
            namespace App;

            [SqlSource.SqlQueries]
            public partial class \u0053ample
            {
                public static string Value => Sql.GetUser;
            }
            """,
            Users
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.Sources.Keys.ShouldContain("App.Sample.g.cs");
    }

    [Fact]
    public void Run_NonAsciiNames_AreKept()
    {
        var run = GeneratorHarness.Run(
            [
                new SourceFile(
                    "/app/Dépôt/Sample.cs",
                    "namespace Données;\n[SqlSource.SqlQueries]\n"
                        + "public partial class Requêtes { public string V => Sql.Größe; }\n"
                ),
            ],
            [new SqlFile("/app/Dépôt/Größe.sql", "SELECT 'ñ 😀';\n")]
        );

        run.Diagnostics.ShouldBeEmpty();
        run.CompilationErrors.ShouldBeEmpty();
        run.GeneratedCodeWarnings.ShouldBeEmpty();
        run.Sources["Données.Requêtes.g.cs"].ShouldContain("public const string Größe = \"SELECT 'ñ 😀';\";");
    }

    [Fact]
    public void Run_AttributeOnTwoPartialDeclarations_IsLeftToTheCompilerAndTheTypeGetsOneFile()
    {
        var run = GeneratorHarness.Run(
            [
                new SourceFile("/app/Repo/Sample.cs", "[SqlSource.SqlQueries]\npublic partial class Sample;\n"),
                new SourceFile("/app/Other/Sample.cs", "[SqlSource.SqlQueries]\npublic partial class Sample;\n"),
            ],
            [Users, new SqlFile("/app/Other/Orders.sql", "SELECT 2;\n")]
        );

        run.Diagnostics.ShouldBeEmpty();
        run.Sources.Keys.ShouldBe(["SqlQueriesAttribute.g.cs", "Sample.g.cs"], ignoreOrder: true);
        run.Sources["Sample.g.cs"].ShouldContain("public const string GetUser");
        run.CompilationErrors.ShouldHaveSingleItem().ShouldStartWith("CS0579 /app/Other/Sample.cs(1,2)");
    }
}
