using System.Collections.Immutable;

namespace SqlSource.Generation;

/// <summary>
/// The attribute and the enums that the generator adds to every project that uses it.
/// </summary>
internal static class AttributeSource
{
    public const string HintName = "SqlSourceGenerateAttribute.g.cs";

    public const string AttributeMetadataName = "SqlSource.SqlSourceGenerateAttribute";

    public const string LocationMetadataName = "SqlSource.SqlLocation";

    public const string OutputMetadataName = "SqlSource.GeneratorOutput";

    public const string PathProperty = "Path";

    public const string LocationProperty = "SqlLocation";

    public const string ParametersProperty = "Parameters";

    public const string OutputProperty = "Output";

    /// <summary>
    /// The metadata name of every type that <see cref="Text" /> declares.  A project that sees the internals of
    /// another one that uses SqlSource sees each of them twice, and <c>AttributeConflictSuppressor</c> turns the
    /// compiler's warning off for exactly these.
    /// </summary>
    public static ImmutableArray<string> GeneratedTypes { get; } =
        ImmutableArray.Create(AttributeMetadataName, LocationMetadataName, OutputMetadataName);

    // Only an attribute class can be [Conditional], so the enums stay in the consumer's assembly.  The attribute
    // itself is not applied in metadata unless the consumer defines SQLSOURCE_ATTRIBUTES.
    //
    // This file goes into every project that references the package, including one that targets a framework older
    // than .NET 8 and so compiles as C# 7.3.  It therefore uses nothing newer: no "#nullable" and no "string?".  Such
    // a project then gets SQLSRC003 if it uses the attribute, not a compiler error in a file it did not write.
    //
    // A project that sees the internals of another one that uses SqlSource gets CS0436 at each use of these types.
    // The pragma below covers the uses in this file, and Diagnostics/AttributeConflictSuppressor.cs the uses in the
    // project's own code.  A type that is added here is added to GeneratedTypes.
    public const string Text = """
        // <auto-generated/>
        // A project that can see the internals of another one that uses SqlSource sees these types twice.
        #pragma warning disable CS0436

        namespace SqlSource
        {
            /// <summary>
            /// Where the members generated for a type marked with <see cref="SqlSourceGenerateAttribute" /> go.
            /// </summary>
            internal enum SqlLocation
            {
                /// <summary>
                /// In a private static class named <c>Sql</c>, nested in the type.
                /// </summary>
                Nested = 0,

                /// <summary>
                /// On the type itself.
                /// </summary>
                Direct = 1,
            }

            /// <summary>
            /// What SqlSource generates for a query.
            /// </summary>
            internal enum GeneratorOutput
            {
                /// <summary>
                /// The SQL: a constant, or a method when the query has a token.
                /// </summary>
                Sql = 0,

                /// <summary>
                /// The SQL, and a type for the query's parameters and one for its result.
                /// </summary>
                Models = 1,

                /// <summary>
                /// The SQL, the types, and a method that runs the query.
                /// </summary>
                CodeGen = 2,
            }

            /// <summary>
            /// Generates a member for each query in the <c>.sql</c> files of the type.
            /// </summary>
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct,
                AllowMultiple = false,
                Inherited = false
            )]
            [global::System.Diagnostics.Conditional("SQLSOURCE_ATTRIBUTES")]
            internal sealed class SqlSourceGenerateAttribute : global::System.Attribute
            {
                /// <summary>
                /// A folder or one <c>.sql</c> file, relative to the folder of the file that carries the attribute.
                /// The default is that folder.
                /// </summary>
                public string Path { get; set; }

                /// <summary>
                /// Where the generated members go.  The default is
                /// <see cref="global::SqlSource.SqlLocation.Nested" />.
                /// </summary>
                public SqlLocation SqlLocation { get; set; }

                /// <summary>
                /// What is generated for the queries of the type's files.  The default is
                /// <see cref="global::SqlSource.GeneratorOutput.CodeGen" />.  A marker in a file comes first.
                /// </summary>
                public GeneratorOutput Output { get; set; }

                /// <summary>
                /// Generator parameters for the queries of the type's files, separated by spaces, as a
                /// <c>-- generator:</c> line holds them.  A line in a file comes first.
                /// </summary>
                public string Parameters { get; set; }
            }
        }

        """;
}
