namespace SqlSource.Generation;

/// <summary>
/// The attribute and the enum that the generator adds to every project that uses it.
/// </summary>
internal static class AttributeSource
{
    public const string HintName = "SqlQueriesAttribute.g.cs";

    public const string AttributeMetadataName = "SqlSource.SqlQueriesAttribute";

    public const string PathProperty = "Path";

    public const string ModeProperty = "Mode";

    // Only an attribute class can be [Conditional], so the enum stays in the consumer's assembly.  The attribute
    // itself is not applied in metadata unless the consumer defines SQLSOURCE_ATTRIBUTES.
    public const string Text = """
        // <auto-generated/>
        #nullable enable

        namespace SqlSource
        {
            /// <summary>
            /// Where the members generated for a type marked with <see cref="SqlQueriesAttribute" /> go.
            /// </summary>
            internal enum SqlQueriesMode
            {
                /// <summary>
                /// In a private static class named <c>Sql</c>, nested in the type.
                /// </summary>
                Nested = 0,

                /// <summary>
                /// On the type itself.
                /// </summary>
                Direct = 1,
            }

            /// <summary>
            /// Generates a member for each query in the <c>.sql</c> files of the type.
            /// </summary>
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct,
                AllowMultiple = false,
                Inherited = false
            )]
            [global::System.Diagnostics.Conditional("SQLSOURCE_ATTRIBUTES")]
            internal sealed class SqlQueriesAttribute : global::System.Attribute
            {
                /// <summary>
                /// A folder or one <c>.sql</c> file, relative to the folder of the file that carries the attribute.
                /// The default is that folder.
                /// </summary>
                public string? Path { get; set; }

                /// <summary>
                /// Where the generated members go.  The default is <see cref="SqlQueriesMode.Nested" />.
                /// </summary>
                public SqlQueriesMode Mode { get; set; }
            }
        }

        """;
}
