using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using SqlSource.Diagnostics;
using SqlSource.Parsing;

namespace SqlSource.Generation;

/// <summary>
/// Writes the generated file of one type.
/// </summary>
internal static class TypeEmitter
{
    /// <summary>
    /// The name of the class that holds the members in <see cref="MemberPlacement.Nested" /> placement.
    /// </summary>
    public const string NestedClassName = "Sql";

    private const string Indent = "    ";

    // A query can be named like a member the type inherits: "GetType" hides object.GetType in the Sql class, and
    // under SqlLocation.Direct a query can hide a member of a base class.  That is what was asked for, and the
    // compiler's request to add "new" (CS0108) is one that nobody can act on in generated code.  Neither is its
    // request to add "new" or "override" (CS0114) to a method that has the name and the parameters of an inherited
    // virtual method.
    private const string Header =
        "// <auto-generated/>\n"
        + "#nullable enable\n"
        + "#pragma warning disable CS0108, CS0114 // A query can have the name of an inherited member.\n"
        + "\n";

    /// <summary>
    /// Writes the file of <paramref name="input" />.
    /// </summary>
    /// <param name="input">The type and its parsed files.</param>
    /// <param name="validateTokens">
    /// What the project asks for: whether a method checks its arguments.  A query's own generator parameter comes
    /// first.
    /// </param>
    public static TypeOutput Emit(TypeQueries input, bool validateTokens)
    {
        var type = input.Type.Type;
        if (input.Type.Diagnostics.Count > 0)
        {
            return new TypeOutput(input.HintName, null, input.Type.Diagnostics);
        }

        var diagnostics = ImmutableArray.CreateBuilder<DiagnosticInfo>();
        var members = SelectMembers(type, input.Files, diagnostics);
        return new TypeOutput(
            input.HintName,
            Write(type, members, validateTokens),
            new EquatableArray<DiagnosticInfo>(diagnostics.ToImmutable())
        );
    }

    // A file contributes all of its queries or none: one that has a query with a name that cannot be used here is
    // left out, with a diagnostic for each such query.
    private static List<(SqlQuery Query, string FileName)> SelectMembers(
        TargetType type,
        EquatableArray<ParsedSqlFile> files,
        ImmutableArray<DiagnosticInfo>.Builder diagnostics
    )
    {
        var containingTypeName = type.Placement == MemberPlacement.Nested ? NestedClassName : type.Name;
        var members = new List<(SqlQuery Query, string FileName)>();
        var fileOfName = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var file in files)
        {
            var isUsable = true;
            foreach (var query in file.Queries)
            {
                if (string.Equals(query.Name, containingTypeName, StringComparison.Ordinal))
                {
                    diagnostics.Add(
                        DiagnosticInfo.Create(
                            SqlDiagnostics.QueryNamedLikeContainingType,
                            query.NameLocation,
                            type.Name,
                            query.Name
                        )
                    );
                    isUsable = false;
                }
                else if (fileOfName.TryGetValue(query.Name, out var firstFile))
                {
                    diagnostics.Add(
                        DiagnosticInfo.Create(
                            SqlDiagnostics.DuplicateQueryName,
                            query.NameLocation,
                            query.Name,
                            firstFile,
                            type.Name
                        )
                    );
                    isUsable = false;
                }
            }

            if (!isUsable)
            {
                continue;
            }

            foreach (var query in file.Queries)
            {
                fileOfName.Add(query.Name, file.FileName);
                members.Add((query, file.FileName));
            }
        }

        return members;
    }

    private static string Write(TargetType type, List<(SqlQuery Query, string FileName)> members, bool validateTokens)
    {
        var builder = new StringBuilder(Header);
        var depth = 0;
        if (type.Namespace.Length > 0)
        {
            Open(builder, depth++, "namespace " + type.Namespace);
        }

        foreach (var declaration in type.Types)
        {
            Open(
                builder,
                depth++,
                "partial " + declaration.Keyword + " " + declaration.Name + declaration.TypeParameters
            );
        }

        if (type.Placement == MemberPlacement.Nested)
        {
            Open(builder, depth++, "private static class " + NestedClassName);
        }

        var indent = GetIndent(depth);
        for (var index = 0; index < members.Count; index++)
        {
            if (index > 0)
            {
                _ = builder.Append('\n');
            }

            var (query, fileName) = members[index];
            var summaryXml = GetSummaryXml(query, fileName);
            if (HasToken(query))
            {
                MethodWriter.Append(
                    builder,
                    indent,
                    summaryXml,
                    query.Name,
                    query.Segments,
                    query.TokenValidation ?? validateTokens
                );
                continue;
            }

            // Without a token the SQL is one literal segment.
            var sql = query.Segments[0].Text;
            XmlDocWriter.AppendMember(builder, indent, summaryXml, sql);
            _ = builder
                .Append(indent)
                .Append("public const string ")
                .Append(query.Name)
                .Append(" = ")
                .Append(SymbolDisplay.FormatLiteral(sql, quote: true))
                .Append(";\n");
        }

        while (depth > 0)
        {
            _ = builder.Append(GetIndent(--depth)).Append("}\n");
        }

        return builder.ToString();
    }

    private static bool HasToken(SqlQuery query)
    {
        foreach (var segment in query.Segments)
        {
            if (segment.Kind == SqlSegmentKind.Token)
            {
                return true;
            }
        }

        return false;
    }

    private static string GetSummaryXml(SqlQuery query, string fileName) =>
        query.Summary is null
            ? "The <c>" + query.Name + "</c> query from <c>" + XmlDocWriter.Escape(fileName) + "</c>."
            : XmlDocWriter.Escape(query.Summary);

    private static void Open(StringBuilder builder, int depth, string header)
    {
        var indent = GetIndent(depth);
        _ = builder.Append(indent).Append(header).Append('\n').Append(indent).Append("{\n");
    }

    private static string GetIndent(int depth) => string.Concat(Enumerable.Repeat(Indent, depth));
}
