using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using SqlSource.Diagnostics;

namespace SqlSource.Generation;

/// <summary>
/// Writes the generated file of one type.
/// </summary>
internal static class TypeEmitter
{
    /// <summary>
    /// The name of the class that holds the members in <see cref="MemberPlacement.Nested" /> placement.
    /// </summary>
    public const string NestedClassName = "Sql";

    private const string Indent = "    ";

    public static TypeOutput Emit(TypeQueries input)
    {
        var type = input.Type.Type;
        var hintName = GetHintName(type);
        if (input.Type.Diagnostics.Count > 0)
        {
            return new TypeOutput(hintName, null, input.Type.Diagnostics);
        }

        var diagnostics = ImmutableArray.CreateBuilder<DiagnosticInfo>();
        var members = SelectMembers(type, input.Files, diagnostics);
        return new TypeOutput(
            hintName,
            Write(type, members),
            new EquatableArray<DiagnosticInfo>(diagnostics.ToImmutable())
        );
    }

    // The namespace and each type name joined with dots.  A generic type's name is followed by its arity, so that
    // Repository and Repository<T> get different files.  Every character is one a hint name may hold.
    private static string GetHintName(TargetType type)
    {
        var name = new StringBuilder(type.Namespace.Replace("@", string.Empty));
        foreach (var declaration in type.Types)
        {
            if (name.Length > 0)
            {
                _ = name.Append('.');
            }

            _ = name.Append(declaration.PlainName);
            if (declaration.Arity > 0)
            {
                _ = name.Append('-').Append(declaration.Arity.ToString(CultureInfo.InvariantCulture));
            }
        }

        return name.Append(".g.cs").ToString();
    }

    // A file contributes all of its queries or none: one that has a query with a name that cannot be used here is
    // left out, with a diagnostic for each such query.
    private static List<(SqlQuery Query, string FileName)> SelectMembers(
        TargetType type,
        EquatableArray<ParsedSqlFile> files,
        ImmutableArray<DiagnosticInfo>.Builder diagnostics
    )
    {
        var containingTypeName = type.Placement == MemberPlacement.Nested ? NestedClassName : type.Name;
        var members = new List<(SqlQuery Query, string FileName)>();
        var fileOfName = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var file in files)
        {
            var isUsable = true;
            foreach (var query in file.Queries)
            {
                if (string.Equals(query.Name, containingTypeName, StringComparison.Ordinal))
                {
                    diagnostics.Add(
                        DiagnosticInfo.Create(
                            SqlDiagnostics.QueryNamedLikeContainingType,
                            query.NameLocation,
                            type.Name,
                            query.Name
                        )
                    );
                    isUsable = false;
                }
                else if (fileOfName.TryGetValue(query.Name, out var firstFile))
                {
                    diagnostics.Add(
                        DiagnosticInfo.Create(
                            SqlDiagnostics.DuplicateQueryName,
                            query.NameLocation,
                            query.Name,
                            firstFile,
                            type.Name
                        )
                    );
                    isUsable = false;
                }
            }

            if (!isUsable)
            {
                continue;
            }

            foreach (var query in file.Queries)
            {
                fileOfName.Add(query.Name, file.FileName);
                members.Add((query, file.FileName));
            }
        }

        return members;
    }

    private static string Write(TargetType type, List<(SqlQuery Query, string FileName)> members)
    {
        var builder = new StringBuilder("// <auto-generated/>\n#nullable enable\n\n");
        var depth = 0;
        if (type.Namespace.Length > 0)
        {
            Open(builder, depth++, "namespace " + type.Namespace);
        }

        foreach (var declaration in type.Types)
        {
            Open(
                builder,
                depth++,
                "partial " + declaration.Keyword + " " + declaration.Name + declaration.TypeParameters
            );
        }

        if (type.Placement == MemberPlacement.Nested)
        {
            Open(builder, depth++, "private static class " + NestedClassName);
        }

        var indent = GetIndent(depth);
        for (var index = 0; index < members.Count; index++)
        {
            if (index > 0)
            {
                _ = builder.Append('\n');
            }

            var (query, fileName) = members[index];
            XmlDocWriter.AppendMember(builder, indent, GetSummaryXml(query, fileName), query.Sql);
            _ = builder
                .Append(indent)
                .Append("public const string ")
                .Append(query.Name)
                .Append(" = ")
                .Append(SymbolDisplay.FormatLiteral(query.Sql, quote: true))
                .Append(";\n");
        }

        while (depth > 0)
        {
            _ = builder.Append(GetIndent(--depth)).Append("}\n");
        }

        return builder.ToString();
    }

    private static string GetSummaryXml(SqlQuery query, string fileName) =>
        query.Summary is null
            ? "The <c>" + query.Name + "</c> query from <c>" + XmlDocWriter.Escape(fileName) + "</c>."
            : XmlDocWriter.Escape(query.Summary);

    private static void Open(StringBuilder builder, int depth, string header)
    {
        var indent = GetIndent(depth);
        _ = builder.Append(indent).Append(header).Append('\n').Append(indent).Append("{\n");
    }

    private static string GetIndent(int depth) => string.Concat(Enumerable.Repeat(Indent, depth));
}
