using System;
using Microsoft.CodeAnalysis.Text;
using Shouldly;
using SqlSource.Diagnostics;
using SqlSource.Generation;
using SqlSource.Parsing;
using Xunit;

namespace SqlSource.Tests.Generation;

public class TypeEmitterTests
{
    [Fact]
    public void Emit_NestedPlacement_PutsTheConstantsInAPrivateSqlClass()
    {
        var users = File(
            "Users.sql",
            Query("GetUser", "SELECT id, name\nFROM users\nWHERE id = @id;", "Loads one user by id."),
            Query("ListUsers", "SELECT id, name FROM users;")
        );

        var output = Emit(TestModels.Type(), users);

        output.HintName.ShouldBe("App.UserRepository.g.cs");
        output.Diagnostics.ShouldBeEmpty();
        output.Source.ShouldBe(
            """
            // <auto-generated/>
            #nullable enable
            #pragma warning disable CS0108 // A query can have the name of an inherited member.

            namespace App
            {
                partial class UserRepository
                {
                    private static class Sql
                    {
                        /// <summary>
                        /// Loads one user by id.
                        /// </summary>
                        /// <remarks>
                        /// <code>
                        /// SELECT id, name
                        /// FROM users
                        /// WHERE id = @id;
                        /// </code>
                        /// </remarks>
                        public const string GetUser = "SELECT id, name\nFROM users\nWHERE id = @id;";

                        /// <summary>
                        /// The <c>ListUsers</c> query from <c>Users.sql</c>.
                        /// </summary>
                        /// <remarks>
                        /// <code>
                        /// SELECT id, name FROM users;
                        /// </code>
                        /// </remarks>
                        public const string ListUsers = "SELECT id, name FROM users;";
                    }
                }
            }

            """
        );
    }

    [Fact]
    public void Emit_DirectPlacement_PutsTheConstantsOnTheType()
    {
        var output = Emit(
            TestModels.Type(placement: MemberPlacement.Direct),
            File("Users.sql", Query("GetUser", "SELECT 1;"))
        );

        output.Source.ShouldBe(
            """
            // <auto-generated/>
            #nullable enable
            #pragma warning disable CS0108 // A query can have the name of an inherited member.

            namespace App
            {
                partial class UserRepository
                {
                    /// <summary>
                    /// The <c>GetUser</c> query from <c>Users.sql</c>.
                    /// </summary>
                    /// <remarks>
                    /// <code>
                    /// SELECT 1;
                    /// </code>
                    /// </remarks>
                    public const string GetUser = "SELECT 1;";
                }
            }

            """
        );
    }

    [Fact]
    public void Emit_NestedGenericTypeInTheGlobalNamespace_RepeatsEachDeclarationAsWritten()
    {
        var type = TestModels.Type(
            @namespace: "",
            types:
            [
                new TypeDeclaration("interface", "IOuter", "IOuter", "<TKey>", 1),
                new TypeDeclaration("record struct", "@class", "class", "<T1, T2>", 2),
                new TypeDeclaration("record", "Inner", "Inner", "", 0),
            ]
        );

        var output = Emit(type, File("Users.sql", Query("GetUser", "SELECT 1;")));

        output.HintName.ShouldBe("IOuter-1.class-2.Inner.g.cs");
        output.Source.ShouldBe(
            """
            // <auto-generated/>
            #nullable enable
            #pragma warning disable CS0108 // A query can have the name of an inherited member.

            partial interface IOuter<TKey>
            {
                partial record struct @class<T1, T2>
                {
                    partial record Inner
                    {
                        private static class Sql
                        {
                            /// <summary>
                            /// The <c>GetUser</c> query from <c>Users.sql</c>.
                            /// </summary>
                            /// <remarks>
                            /// <code>
                            /// SELECT 1;
                            /// </code>
                            /// </remarks>
                            public const string GetUser = "SELECT 1;";
                        }
                    }
                }
            }

            """
        );
    }

    [Fact]
    public void Emit_NamespaceWithAnEscapedKeyword_KeepsItInCodeAndDropsItFromTheHintName()
    {
        var output = Emit(
            TestModels.Type(@namespace: "App.@event.Data"),
            File("Users.sql", Query("GetUser", "SELECT 1;"))
        );

        output.HintName.ShouldBe("App.event.Data.UserRepository.g.cs");
        output.Source.ShouldNotBeNull().ShouldContain("namespace App.@event.Data\n{\n");
    }

    [Fact]
    public void Emit_SqlWithCharactersThatNeedEscaping_EscapesTheLiteralAndTheCommentSeparately()
    {
        const string Sql = "SELECT \"a\", 'b\\c', '\t' WHERE x < 1 && y > 2;";

        var output = Emit(TestModels.Type(), File("A&B.sql", Query("GetUser", Sql)));

        var source = output.Source.ShouldNotBeNull();
        source.ShouldContain("/// The <c>GetUser</c> query from <c>A&amp;B.sql</c>.\n");
        source.ShouldContain("/// SELECT \"a\", 'b\\c', '\t' WHERE x &lt; 1 &amp;&amp; y &gt; 2;\n");
        source.ShouldContain(
            "public const string GetUser = \"SELECT \\\"a\\\", 'b\\\\c', '\\t' WHERE x < 1 && y > 2;\";\n"
        );
    }

    [Fact]
    public void Emit_SummaryWithCharactersXmlReserves_EscapesThem()
    {
        var output = Emit(
            TestModels.Type(),
            File("Users.sql", Query("GetUser", "SELECT 1;", "Users <b>with</b> a & b."))
        );

        output.Source.ShouldNotBeNull().ShouldContain("/// Users &lt;b&gt;with&lt;/b&gt; a &amp; b.\n");
    }

    [Fact]
    public void Emit_SeveralFiles_KeepsTheOrderOfTheFilesAndOfTheQueriesInEach()
    {
        var output = Emit(
            TestModels.Type(placement: MemberPlacement.Direct),
            File("B.sql", Query("Zeta", "SELECT 1;"), Query("Alpha", "SELECT 2;")),
            File("A.sql", Query("Mid", "SELECT 3;"))
        );

        var source = output.Source.ShouldNotBeNull();
        source.IndexOf("const string Zeta", StringComparison.Ordinal).ShouldBeGreaterThan(0);
        source
            .IndexOf("const string Alpha", StringComparison.Ordinal)
            .ShouldBeGreaterThan(source.IndexOf("const string Zeta", StringComparison.Ordinal));
        source
            .IndexOf("const string Mid", StringComparison.Ordinal)
            .ShouldBeGreaterThan(source.IndexOf("const string Alpha", StringComparison.Ordinal));
    }

    [Fact]
    public void Emit_TypeWithAProblem_GetsNoSourceAndKeepsTheProblem()
    {
        var problem = DiagnosticInfo.Create(
            SqlDiagnostics.TypeNotPartial,
            TestModels.AttributeLocation,
            "UserRepository"
        );
        var typeFiles = new TypeFiles(
            TestModels.Type(),
            TestModels.Array("app/Repo/Users.sql"),
            TestModels.Array(problem)
        );

        var output = TypeEmitter.Emit(
            new TypeQueries(
                typeFiles,
                TestModels.Array(File("Users.sql", Query("GetUser", "SELECT 1;"))),
                "App.UserRepository.g.cs"
            ),
            validateTokens: true
        );

        output.ShouldBe(new TypeOutput("App.UserRepository.g.cs", null, TestModels.Array(problem)));
    }

    [Fact]
    public void Emit_QueryNameAlreadyUsedByAnEarlierFile_IsAnErrorAndTheLaterFileGivesNoMembers()
    {
        var output = Emit(
            TestModels.Type(),
            File("A.sql", Query("GetUser", "SELECT 1;")),
            File("B.sql", Query("Other", "SELECT 2;"), Query("GetUser", "SELECT 3;", file: "B.sql")),
            File("C.sql", Query("Other", "SELECT 4;"))
        );

        output.Diagnostics.ShouldBe([
            DiagnosticInfo.Create(
                SqlDiagnostics.DuplicateQueryName,
                NameLocation("B.sql"),
                "GetUser",
                "A.sql",
                "UserRepository"
            ),
        ]);
        var source = output.Source.ShouldNotBeNull();
        source.ShouldContain("public const string GetUser = \"SELECT 1;\";");
        source.ShouldContain("public const string Other = \"SELECT 4;\";");
        source.ShouldNotContain("SELECT 2;");
        source.ShouldNotContain("SELECT 3;");
    }

    [Theory]
    [InlineData(false, "Sql")]
    [InlineData(true, "UserRepository")]
    public void Emit_QueryNamedLikeTheTypeItsMemberGoesIn_IsAnErrorAndItsFileGivesNoMembers(bool direct, string name)
    {
        var output = Emit(
            TestModels.Type(placement: Placement(direct)),
            File("A.sql", Query(name, "SELECT 1;"), Query("Other", "SELECT 2;")),
            File("B.sql", Query("Kept", "SELECT 3;"))
        );

        output.Diagnostics.ShouldBe([
            DiagnosticInfo.Create(
                SqlDiagnostics.QueryNamedLikeContainingType,
                NameLocation("Users.sql"),
                "UserRepository",
                name
            ),
        ]);
        var source = output.Source.ShouldNotBeNull();
        source.ShouldContain("public const string Kept = \"SELECT 3;\";");
        source.ShouldNotContain("SELECT 1;");
        source.ShouldNotContain("SELECT 2;");
    }

    [Theory]
    [InlineData(false, "UserRepository")]
    [InlineData(true, "Sql")]
    [InlineData(false, "sql")]
    public void Emit_QueryNamedLikeTheOtherPlacementsType_IsAllowed(bool direct, string name)
    {
        var output = Emit(TestModels.Type(placement: Placement(direct)), File("A.sql", Query(name, "SELECT 1;")));

        output.Diagnostics.ShouldBeEmpty();
        output.Source.ShouldNotBeNull().ShouldContain("public const string " + name + " = \"SELECT 1;\";");
    }

    [Fact]
    public void Emit_QueryWithAToken_IsAMethodInTheSamePlaceAndOrderAsTheConstants()
    {
        var output = Emit(
            TestModels.Type(),
            File("Users.sql", Query("GetUser", "SELECT 1;"), TokenQuery("ListFrom"), Query("Count", "SELECT 3;"))
        );

        output.Diagnostics.ShouldBeEmpty();
        output.Source.ShouldBe(
            """
            // <auto-generated/>
            #nullable enable
            #pragma warning disable CS0108 // A query can have the name of an inherited member.

            namespace App
            {
                partial class UserRepository
                {
                    private static class Sql
                    {
                        /// <summary>
                        /// The <c>GetUser</c> query from <c>Users.sql</c>.
                        /// </summary>
                        /// <remarks>
                        /// <code>
                        /// SELECT 1;
                        /// </code>
                        /// </remarks>
                        public const string GetUser = "SELECT 1;";

                        /// <summary>
                        /// The <c>ListFrom</c> query from <c>Users.sql</c>.
                        /// </summary>
                        /// <remarks>
                        /// <code>
                        /// SELECT * FROM {{table}};
                        /// </code>
                        /// </remarks>
                        /// <param name="table">The text that replaces <c>{{table}}</c>.</param>
                        public static string ListFrom(string table)
                        {
                            global::System.ArgumentException.ThrowIfNullOrWhiteSpace(table);
                            return string.Create(
                                15 + table.Length,
                                table,
                                static (span, state) =>
                                {
                                    "SELECT * FROM ".CopyTo(span);
                                    span = span.Slice(14);
                                    state.CopyTo(span);
                                    span = span.Slice(state.Length);
                                    ";".CopyTo(span);
                                }
                            );
                        }

                        /// <summary>
                        /// The <c>Count</c> query from <c>Users.sql</c>.
                        /// </summary>
                        /// <remarks>
                        /// <code>
                        /// SELECT 3;
                        /// </code>
                        /// </remarks>
                        public const string Count = "SELECT 3;";
                    }
                }
            }

            """
        );
    }

    [Fact]
    public void Emit_QueryWithATokenInDirectPlacement_IsAMethodOnTheType()
    {
        var output = Emit(
            TestModels.Type(placement: MemberPlacement.Direct),
            File("Users.sql", TokenQuery("ListFrom"))
        );

        var source = output.Source.ShouldNotBeNull();
        source.ShouldContain("    {\n        /// <summary>\n        /// The <c>ListFrom</c> query from");
        source.ShouldContain("        public static string ListFrom(string table)\n        {\n");
        source.ShouldNotContain("class Sql");
    }

    // The query's own directive, then what the project asks for.
    [Theory]
    [InlineData(null, true, true)]
    [InlineData(null, false, false)]
    [InlineData(true, false, true)]
    [InlineData(true, true, true)]
    [InlineData(false, true, false)]
    [InlineData(false, false, false)]
    public void Emit_QueryWithAToken_ValidatesByItsDirectiveAndThenByTheProject(
        bool? directive,
        bool project,
        bool expected
    )
    {
        var output = Emit(TestModels.Type(), project, File("Users.sql", TokenQuery("ListFrom", directive)));

        var source = output.Source.ShouldNotBeNull();
        if (expected)
        {
            source.ShouldContain("global::System.ArgumentException.ThrowIfNullOrWhiteSpace(table);\n");
        }
        else
        {
            source.ShouldNotContain("Throw");
        }
    }

    [Fact]
    public void Emit_ValidationOff_LeavesAConstantAsItIs()
    {
        var files = File("Users.sql", Query("GetUser", "SELECT 1;"));

        Emit(TestModels.Type(), validateTokens: false, files).ShouldBe(Emit(TestModels.Type(), files));
    }

    [Fact]
    public void Emit_MethodNamedLikeAConstantOfAnEarlierFile_IsTheSameErrorAsForTwoConstants()
    {
        var output = Emit(
            TestModels.Type(),
            File("A.sql", Query("GetUser", "SELECT 1;")),
            File("B.sql", TokenQuery("GetUser", file: "B.sql"))
        );

        output.Diagnostics.ShouldBe([
            DiagnosticInfo.Create(
                SqlDiagnostics.DuplicateQueryName,
                NameLocation("B.sql"),
                "GetUser",
                "A.sql",
                "UserRepository"
            ),
        ]);
        output.Source.ShouldNotBeNull().ShouldNotContain("public static string GetUser");
    }

    [Fact]
    public void Emit_MethodNamedLikeTheSqlClass_IsTheSameErrorAsForAConstant()
    {
        var output = Emit(TestModels.Type(), File("Users.sql", TokenQuery("Sql")));

        output.Diagnostics.ShouldHaveSingleItem().Descriptor.ShouldBe(SqlDiagnostics.QueryNamedLikeContainingType);
        output.Source.ShouldNotBeNull().ShouldNotContain("public static string Sql");
    }

    [Fact]
    public void Emit_TypeWhoseFilesGiveNoMembers_StillGetsItsEmptySqlClass()
    {
        var output = Emit(TestModels.Type(), File("Users.sql"));

        output.Source.ShouldBe(
            """
            // <auto-generated/>
            #nullable enable
            #pragma warning disable CS0108 // A query can have the name of an inherited member.

            namespace App
            {
                partial class UserRepository
                {
                    private static class Sql
                    {
                    }
                }
            }

            """
        );
    }

    [Fact]
    public void Emit_SameInput_GivesEqualOutput()
    {
        static TypeOutput Create() => Emit(TestModels.Type(), File("Users.sql", Query("GetUser", "SELECT 1;")));

        Create().ShouldBe(Create());
    }

    // A theory cannot take the internal enum as a parameter.
    private static MemberPlacement Placement(bool direct) => direct ? MemberPlacement.Direct : MemberPlacement.Nested;

    private static TypeOutput Emit(TargetType type, params ParsedSqlFile[] files) =>
        Emit(type, validateTokens: true, files);

    private static TypeOutput Emit(TargetType type, bool validateTokens, params ParsedSqlFile[] files) =>
        TypeEmitter.Emit(
            new TypeQueries(
                new TypeFiles(type, TestModels.Array<string>(), TestModels.Array<DiagnosticInfo>()),
                TestModels.Array(files),
                HintName.Create(type)
            ),
            validateTokens
        );

    private static ParsedSqlFile File(string fileName, params SqlQuery[] queries) =>
        new("app/Repo/" + fileName, fileName, TestModels.Array(queries), TestModels.Array<DiagnosticInfo>());

    private static SqlQuery Query(string name, string sql, string? summary = null, string file = "Users.sql") =>
        new(name, NameLocation(file), summary, TestModels.Array(new SqlSegment(SqlSegmentKind.Literal, sql)), null);

    // "SELECT * FROM {{table}};", which is a method with one parameter.
    private static SqlQuery TokenQuery(string name, bool? tokenValidation = null, string file = "Users.sql") =>
        new(
            name,
            NameLocation(file),
            null,
            TestModels.Array(
                new SqlSegment(SqlSegmentKind.Literal, "SELECT * FROM "),
                new SqlSegment(SqlSegmentKind.Token, "table"),
                new SqlSegment(SqlSegmentKind.Literal, ";")
            ),
            tokenValidation
        );

    private static LocationInfo NameLocation(string file) =>
        new(
            "/app/Repo/" + file,
            new TextSpan(9, 7),
            new LinePositionSpan(new LinePosition(0, 9), new LinePosition(0, 16))
        );
}
